export const environment = {
  production: true,
  prefillLoginForm: true,
  displayProcessesInfo: true,
  debugBlockUnblockUI:true,
  apiURL: "http://localhost:8093/",
  apiURLForFiles: "http://localhost:8093/",
  numberOfSecondsBetweenRefreshOfMessages: 120,
  numberOfSecondsBetweenChecksOfVersion: 120,
  frontEndVersion:"2020-11-11.02",
  jwt_name: "traquer_jwt",
  defaultNumberOfResults:50,
  numberOfResultsForDeals: 50,
  numberOfResultsForDesigns: 25,
  numberOfResultsForForumMessages: 40,
  numberOfResultsForDashboard:10,
  hideTrademarksModule:true,
  hideSalesReportsModule:false,
  maxFileSizeInMByteForRasterImages:1,
  maxFileSizeInMByteForOtherFiles:1,
};
