export enum SAMPLE_MATERIAL_TYPE {

    faeces = 1, 
    urine = 2, 
    heart_blood = 3, 
    peripheral_blood = 4, 
    saliva = 5, 
    heart = 6, 
    thoracic_aorta = 7, 
    abdominal_aorta = 8, 
    esophagus = 9, 
    trachea = 10, 
    stomach = 11, 
    digestive_tract = 12, 
    prostate = 13, 
    uterus = 14, 
    ovaries = 15, 
    adrenal_glands = 16, 
    liver = 17, 
    brain = 18, 
    rein = 19, 
    lung = 20, 
    bone_marrow = 21, 
    spinal_cord = 22, 
    bone = 23, 
    muscle = 24, 
    skin = 25, 
    laringo = 26, 
    spleen = 27, 
    pancreas = 28, 
    nails = 29, 
    gastric_contents = 30, 
    unidentified_liquid = 31, 
    vitreous_humour = 32, 
    hair = 33, 
    bile = 34, 
    textile = 35, 
    prosthetic_material = 36, 
    ballistic_material = 37, 
    other = 38, 

}