#!/usr/bin/env bash
# patch-primeng-templates.sh
#
# PrimeNG 13 uses `in` as a template reference variable in
# `multiselect` and `terminal`. Modern Angular (>= 17) template
# parsers choke on this because `in` is a JavaScript reserved word.
#
# We rename `in` -> `inRef` in both the template-ref declaration
# and every binding that reads it. The compiled `.mjs` files are
# regenerated by Angular CLI on every build, but PrimeNG ships
# already-compiled `.mjs` artefacts in node_modules, so we patch
# them in place.
#
# Run this AFTER `npm install`. Safe to run multiple times.
#
# Usage: ./scripts/patch-primeng-templates.sh

set -euo pipefail

primeng_dir="${PRIMENG_DIR:-node_modules/primeng}"
shoptglob=""

for dir in fesm2020 fesm2015 ; do
  for component in multiselect terminal ; do
    file="${primeng_dir}/${dir}/primeng-${component}.mjs"
    if [ ! -f "$file" ] ; then
      continue
    fi

    before=$(grep -c "(click)=\"onMouseclick(\$event,in)\"" "$file" || true)
    if [ "$before" -gt 0 ] ; then
      sed -i 's|#in\b|inRef|g' "$file"
      sed -i 's|onMouseclick(\$event,in)|onMouseclick(\$event,inRef)|g' "$file"
      sed -i 's|focus(in)|focus(inRef)|g' "$file"
      echo "patched $file"
    fi
  done
done

echo "Done."
